server:
  port: 8989


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_board?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 626512
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    defer-datasource-initialization: true